/* This file is generated by Ziggy. */
import { route as routeFn } from 'ziggy-js'

declare global {
    var route: typeof routeFn;
}

declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "dashboard": [],
    "posts.index": [],
    "posts.create": [],
    "posts.store": [],
    "posts.show": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.edit": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.update": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.destroy": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "reactions.store": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "user-password.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
